export const SAVE_CREDENTIALS_START = 'SAVE_CREDENTIALS_START'
export const SAVE_CREDENTIALS_SUCCESS = 'SAVE_CREDENTIALS_SUCCESS'
export const SAVE_CREDENTIALS_FAIL = 'SAVE_CREDENTIALS_FAIL'

export const SIGNUP_START = 'SIGNUP_START'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'