export const SAVE_CREDENTIALS_START = 'SAVE_CREDENTIALS_START'
export const SAVE_CREDENTIALS_SUCCESS = 'SAVE_CREDENTIALS_SUCCESS'
export const SAVE_CREDENTIALS_FAIL = 'SAVE_CREDENTIALS_FAIL'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

//export const GET_USER_START = 'GET_USER_START'
//export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
//export const GET_USER_FAIL = 'GET_USER_FAIL'